//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace org.willowcreek.CareCenter.Migrations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CareCenterMigrationsSQL {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CareCenterMigrationsSQL() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("org.willowcreek.CareCenter.Migrations.CareCenterMigrationsSQL", typeof(CareCenterMigrationsSQL).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        ///&lt;doc&gt;
        ///	&lt;summary&gt;
        /// 		This stored procedure updates several attributes related to a person&apos;s
        ///		attendance.
        ///	&lt;/summary&gt;
        ///	
        ///	&lt;remarks&gt;	
        ///		For eRA we only consider adults for the critieria.
        ///	&lt;/remarks&gt;
        ///	&lt;code&gt;
        ///		EXEC [dbo].[spCrm_FamilyAnalyticsAttendance] 
        ///	&lt;/code&gt;
        ///&lt;/doc&gt;
        ///*/
        ///
        ///ALTER PROCEDURE [dbo].[spCrm_FamilyAnalyticsAttendance]
        ///	
        ///AS
        ///BEGIN
        ///	
        ///	-- configuration of the duration in weeks
        ///	DECLARE @EntryAttendanceDurationWeeks int = 16
        ///		
        ///	DECLARE @cACTIVE_RECORD_STATUS_VALUE_GUID uniquei [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _011_AddResourceDirectory {
            get {
                return ResourceManager.GetString("_011_AddResourceDirectory", resourceCulture);
            }
        }
    }
}
