//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rock.CodeGeneration project
//     Changes to this file will be lost when the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// <copyright>
// Copyright by the Spark Development Network
//
// Licensed under the Rock Community License (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.rockrms.com/license
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// </copyright>
//
using System;
using System.Linq;

using Rock.Data;

namespace org.willowcreek.CareCenter.Model
{
    /// <summary>
    /// Resource Service class
    /// </summary>
    public partial class ResourceService : Service<Resource>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ResourceService"/> class
        /// </summary>
        /// <param name="context">The context.</param>
        public ResourceService(RockContext context) : base(context)
        {
        }

        /// <summary>
        /// Determines whether this instance can delete the specified item.
        /// </summary>
        /// <param name="item">The item.</param>
        /// <param name="errorMessage">The error message.</param>
        /// <returns>
        ///   <c>true</c> if this instance can delete the specified item; otherwise, <c>false</c>.
        /// </returns>
        public bool CanDelete( Resource item, out string errorMessage )
        {
            errorMessage = string.Empty;
            return true;
        }
    }

    /// <summary>
    /// Generated Extension Methods
    /// </summary>
    public static partial class ResourceExtensionMethods
    {
        /// <summary>
        /// Clones this Resource object to a new Resource object
        /// </summary>
        /// <param name="source">The source.</param>
        /// <param name="deepCopy">if set to <c>true</c> a deep copy is made. If false, only the basic entity properties are copied.</param>
        /// <returns></returns>
        public static Resource Clone( this Resource source, bool deepCopy )
        {
            if (deepCopy)
            {
                return source.Clone() as Resource;
            }
            else
            {
                var target = new Resource();
                target.CopyPropertiesFrom( source );
                return target;
            }
        }

        /// <summary>
        /// Copies the properties from another Resource object to this Resource object
        /// </summary>
        /// <param name="target">The target.</param>
        /// <param name="source">The source.</param>
        public static void CopyPropertiesFrom( this Resource target, Resource source )
        {
            target.Id = source.Id;
            target.City = source.City;
            target.County = source.County;
            target.Description = source.Description;
            target.EmailAddress = source.EmailAddress;
            target.FirstName = source.FirstName;
            target.ForeignGuid = source.ForeignGuid;
            target.ForeignKey = source.ForeignKey;
            target.GeoPoint = source.GeoPoint;
            target.InterviewDateTime = source.InterviewDateTime;
            target.IsActive = source.IsActive;
            target.LastName = source.LastName;
            target.MobileNumber = source.MobileNumber;
            target.Name = source.Name;
            target.OwnerValueId = source.OwnerValueId;
            target.PhoneNumber = source.PhoneNumber;
            target.PostalCode = source.PostalCode;
            target.ReducedFeeProgramParticpant = source.ReducedFeeProgramParticpant;
            target.SlidingFeeOffered = source.SlidingFeeOffered;
            target.State = source.State;
            target.Street = source.Street;
            target.SupportGroupsOfferred = source.SupportGroupsOfferred;
            target.TypeValueId = source.TypeValueId;
            target.Website = source.Website;
            target.WillowAttender = source.WillowAttender;
            target.CreatedDateTime = source.CreatedDateTime;
            target.ModifiedDateTime = source.ModifiedDateTime;
            target.CreatedByPersonAliasId = source.CreatedByPersonAliasId;
            target.ModifiedByPersonAliasId = source.ModifiedByPersonAliasId;
            target.Guid = source.Guid;
            target.ForeignId = source.ForeignId;

        }
    }
}
